---
# handlers file for monitoring_server

 - name: restart sensu
   service:
     name: "{{item}}"
     state: restarted
     enabled: yes
   with_items:
     - "sensu-server"
     - "sensu-api"
     - "uchiwa"

 
